### ISSUE TITLE
代码执行环境请教

### ISSUE THREAD

**Issue by timqi** [EtherDream/jsproxy-browser#11]
https://github.com/EtherDream/jsproxy-browser/blob/a7a6d740e2c64b1a029fe9ced8ffe9f786e154dd/src/proxy/src/index.js#L57-L65

上面代码中的 pageEnv 应该是注入的 help.js，swEnv 应该是浏览器的 service worker，最后那个 workerEnv 是什么环境执行的？

**Comment by EtherDream** [comment]
注入到页面创建的 Worker / SharedWorker 里，hook  一些 url 相关的 API

**Comment by timqi** [comment]
在哪注入的啊，方便指出相关代码吗？

**Comment by timqi** [comment]
另外希望能添加根据域名决定是否代理的功能，比如 google 出来的的结果可能是一些内网内容，代理之后反而不方便查看。可以合并 #10 或者作者单独开发一下

**Comment by EtherDream** [comment]
好的
