### ISSUE TITLE
脚本运行

### ISSUE THREAD

**Issue by qwqdanchun** [EtherDream/jsproxy-browser#3]
想问一个问题，这两个脚本为什么我运行不了呢
提示proxy/debug.sh: line 2: webpack: command not found

**Comment by EtherDream** [comment]
> webpack

目前需要安装 webpack 工具。过几天我改成动态配置，不再需要这个工具

**Comment by qwqdanchun** [comment]
刚才在网上看了好久，实在有些没弄懂这个webpack要怎么打包(真的太菜了)，
可以麻烦您帮我生成一下吗，只保留一个洛杉矶搬瓦工线路就好，域名jsproxy.dcyy.fun:8443
万分感谢！


ps:这个项目可以赞助或者支持作者吗，它真的帮了我很大的忙，非常感谢作者的付出，谢谢您了


 
---原始邮件---
发件人: "EtherDream"<notifications@github.com>
发送时间: 2019年5月23日(星期四) 上午10:13
收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"qwqdanchun"<287182701@qq.com>;
主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3)


 
webpack
  
目前需要安装 webpack 工具。过几天我改成动态配置，不再需要这个工具

**Comment by EtherDream** [comment]
> webpack

先安装 nodejs，然后安装 webpack，网上搜下就有了。

**Comment by qwqdanchun** [comment]
> > webpack
> 
> 先安装 nodejs，然后安装 webpack，网上搜下就有了。

nodejs很好装，但是webpack已经装了10多次了，各种版本各种报错。。。
求大佬帮忙打个包吧，实在被webpack折腾惨了，谢谢了

**Comment by a3587556** [comment]
> > > webpack
> > 
> > 
> > 先安装 nodejs，然后安装 webpack，网上搜下就有了。
> 
> nodejs很好装，但是webpack已经装了10多次了，各种版本各种报错。。。
> 求大佬帮忙打个包吧，实在被webpack折腾惨了，谢谢了

你指定下webpack版本试试
npm install webpack@3.0.0 -g

**Comment by qwqdanchun** [comment]
这次安装好了，灰常感谢你的建议，但是又出了一点小问题


这种该如何处理呢？
------------------ 原始邮件 ------------------
发件人: "a3587556"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 下午4:04
收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>;
抄送: "287182701"<287182701@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3)



   
webpack
  
先安装 nodejs，然后安装 webpack，网上搜下就有了。
  
nodejs很好装，但是webpack已经装了10多次了，各种版本各种报错。。。
 求大佬帮忙打个包吧，实在被webpack折腾惨了，谢谢了
  
你指定下webpack版本试试
 npm install webpack@3.0.0 -g

**Comment by qwqdanchun** [comment]
显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗

**Comment by a3587556** [comment]
> 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗

webpack 和 httpmini 安装的时候最后-g 全局安装即可

**Comment by EtherDream** [comment]
> 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗

现在支持动态配置了，clone dev 分支试试。https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改 conf.js 就可以了，不用打包。

**Comment by qwqdanchun** [comment]
哇，这就去试，
超级感谢
 
---原始邮件---
发件人: "EtherDream"<notifications@github.com>
发送时间: 2019年5月24日(星期五) 上午10:47
收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"qwqdanchun"<287182701@qq.com>;
主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3)


 
显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗
  
现在支持动态配置了，clone dev 分支试试。https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改 conf.js 就可以了，不用打包。

**Comment by EtherDream** [comment]
> 哇，这就去试， 超级感谢
> […](#)
> ---原始邮件--- 发件人: "EtherDream"<notifications@github.com> 发送时间: 2019年5月24日(星期五) 上午10:47 收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>; 抄送: "Author"<author@noreply.github.com>;"qwqdanchun"<287182701@qq.com>; 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗 现在支持动态配置了，clone dev 分支试试。[https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改](https://github.com/EtherDream/jsproxy-browser/tree/dev/www%E3%80%82%E4%BF%AE%E6%94%B9) conf.js 就可以了，不用打包。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

还在测试中，定期 pull 一下，有问题反馈

**Comment by qwqdanchun** [comment]
这种报错是哪里没配置好吗
 
---原始邮件---
发件人: "EtherDream"<notifications@github.com>
发送时间: 2019年5月24日(星期五) 上午10:50
收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"qwqdanchun"<287182701@qq.com>;
主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3)


 
哇，这就去试， 超级感谢
 …
 ---原始邮件--- 发件人: "EtherDream"notifications@github.com 发送时间: 2019年5月24日(星期五) 上午10:47 收件人: "EtherDream/jsproxy-browser"jsproxy-browser@noreply.github.com; 抄送: "Author"author@noreply.github.com;"qwqdanchun"287182701@qq.com; 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗 现在支持动态配置了，clone dev 分支试试。https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改 conf.js 就可以了，不用打包。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
还在测试中，定期 pull 一下，有问题反馈

**Comment by qwqdanchun** [comment]
> 这种报错是哪里没配置好吗

**Comment by EtherDream** [comment]
> 这种报错是哪里没配置好吗
> […](#)
> ---原始邮件--- 发件人: "EtherDream"<notifications@github.com> 发送时间: 2019年5月24日(星期五) 上午10:50 收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>; 抄送: "Author"<author@noreply.github.com>;"qwqdanchun"<287182701@qq.com>; 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 哇，这就去试， 超级感谢 … ---原始邮件--- 发件人: "EtherDream"notifications@github.com 发送时间: 2019年5月24日(星期五) 上午10:47 收件人: "EtherDream/jsproxy-browser"jsproxy-browser@noreply.github.com; 抄送: "Author"author@noreply.github.com;"qwqdanchun"287182701@qq.com; 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗 现在支持动态配置了，clone dev 分支试试。[https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改](https://github.com/EtherDream/jsproxy-browser/tree/dev/www%E3%80%82%E4%BF%AE%E6%94%B9) conf.js 就可以了，不用打包。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 还在测试中，定期 pull 一下，有问题反馈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

是说 webpack 的报错吗？

**Comment by qwqdanchun** [comment]
> > 这种报错是哪里没配置好吗
> > […](#)
> > ---原始邮件--- 发件人: "EtherDream"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年5月24日(星期五) 上午10:50 收件人: "EtherDream/jsproxy-browser"[jsproxy-browser@noreply.github.com](mailto:jsproxy-browser@noreply.github.com); 抄送: "Author"[author@noreply.github.com](mailto:author@noreply.github.com);"qwqdanchun"[287182701@qq.com](mailto:287182701@qq.com); 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 哇，这就去试， 超级感谢 … ---原始邮件--- 发件人: "EtherDream"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年5月24日(星期五) 上午10:47 收件人: "EtherDream/jsproxy-browser"[jsproxy-browser@noreply.github.com](mailto:jsproxy-browser@noreply.github.com); 抄送: "Author"[author@noreply.github.com](mailto:author@noreply.github.com);"qwqdanchun"[287182701@qq.com](mailto:287182701@qq.com); 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗 现在支持动态配置了，clone dev 分支试试。[https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改](https://github.com/EtherDream/jsproxy-browser/tree/dev/www%E3%80%82%E4%BF%AE%E6%94%B9) conf.js 就可以了，不用打包。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 还在测试中，定期 pull 一下，有问题反馈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 是说 webpack 的报错吗？

![Screenshot_2019-05-24-12-09-25-414_mark via](https://user-images.githubusercontent.com/48477028/58313076-51af6780-7e3f-11e9-8657-e626cc7537e8.png)

**Comment by EtherDream** [comment]
> > > 这种报错是哪里没配置好吗
> > > […](#)
> > > ---原始邮件--- 发件人: "EtherDream"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年5月24日(星期五) 上午10:50 收件人: "EtherDream/jsproxy-browser"[jsproxy-browser@noreply.github.com](mailto:jsproxy-browser@noreply.github.com); 抄送: "Author"[author@noreply.github.com](mailto:author@noreply.github.com);"qwqdanchun"[287182701@qq.com](mailto:287182701@qq.com); 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 哇，这就去试， 超级感谢 … ---原始邮件--- 发件人: "EtherDream"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年5月24日(星期五) 上午10:47 收件人: "EtherDream/jsproxy-browser"[jsproxy-browser@noreply.github.com](mailto:jsproxy-browser@noreply.github.com); 抄送: "Author"[author@noreply.github.com](mailto:author@noreply.github.com);"qwqdanchun"[287182701@qq.com](mailto:287182701@qq.com); 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗 现在支持动态配置了，clone dev 分支试试。[https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改](https://github.com/EtherDream/jsproxy-browser/tree/dev/www%E3%80%82%E4%BF%AE%E6%94%B9) conf.js 就可以了，不用打包。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 还在测试中，定期 pull 一下，有问题反馈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 是说 webpack 的报错吗？
> 
> ![Screenshot_2019-05-24-12-09-25-414_mark via](https://user-images.githubusercontent.com/48477028/58313076-51af6780-7e3f-11e9-8657-e626cc7537e8.png)

你用隐身模式打开试试？

**Comment by qwqdanchun** [comment]
隐身也没有用，显示TypeError: Failed to fetch
要不你可以访问下看看，https://qwqdanchun.github.io




------------------ 原始邮件 ------------------
发件人: "EtherDream"<notifications@github.com>;
发送时间: 2019年5月24日(星期五) 下午4:17
收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>;
抄送: "287182701"<287182701@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3)



   
这种报错是哪里没配置好吗
 …
 ---原始邮件--- 发件人: "EtherDream"notifications@github.com 发送时间: 2019年5月24日(星期五) 上午10:50 收件人: "EtherDream/jsproxy-browser"jsproxy-browser@noreply.github.com; 抄送: "Author"author@noreply.github.com;"qwqdanchun"287182701@qq.com; 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 哇，这就去试， 超级感谢 … ---原始邮件--- 发件人: "EtherDream"notifications@github.com 发送时间: 2019年5月24日(星期五) 上午10:47 收件人: "EtherDream/jsproxy-browser"jsproxy-browser@noreply.github.com; 抄送: "Author"author@noreply.github.com;"qwqdanchun"287182701@qq.com; 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) 显示安装webpack成功了，但是webpack命令和httpmini那个命令都提示找不到命令，是我装的还有问题吗 现在支持动态配置了，clone dev 分支试试。https://github.com/EtherDream/jsproxy-browser/tree/dev/www。修改 conf.js 就可以了，不用打包。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 还在测试中，定期 pull 一下，有问题反馈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
是说 webpack 的报错吗？
  

  
你用隐身模式打开试试？

**Comment by EtherDream** [comment]
> https://qwqdanchun.github.io

访问 https://jsproxy.dcyy.fun:8443/http 提示 HTTPS 证书有问题。

**Comment by qwqdanchun** [comment]
证书处理好了，https访问没问题，但是报错还在




------------------ 原始邮件 ------------------
发件人: "EtherDream"<notifications@github.com>;
发送时间: 2019年5月24日(星期五) 下午4:31
收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>;
抄送: "287182701"<287182701@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3)



 
https://qwqdanchun.github.io
  
访问 https://jsproxy.dcyy.fun:8443/http 提示 HTTPS 证书有问题。

**Comment by EtherDream** [comment]
> 证书处理好了，https访问没问题，但是报错还在
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "EtherDream"<notifications@github.com>; 发送时间: 2019年5月24日(星期五) 下午4:31 收件人: "EtherDream/jsproxy-browser"<jsproxy-browser@noreply.github.com>; 抄送: "287182701"<287182701@qq.com>;"State change"<state_change@noreply.github.com>; 主题: Re: [EtherDream/jsproxy-browser] 脚本运行 (#3) https://qwqdanchun.github.io 访问 https://jsproxy.dcyy.fun:8443/http 提示 HTTPS 证书有问题。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

用隐身模式试了下貌似没问题了。

**Comment by qwqdanchun** [comment]
刚才忘记清缓存了，确实好了，谢谢你这两天的帮助，灰常感激
