### ISSUE TITLE
关于使用消息传递的方式设置Cookie的疑问

### ISSUE THREAD

**Issue by Dixeran** [EtherDream/jsproxy-browser#4]
https://github.com/EtherDream/jsproxy-browser/blob/e35b1af26be54a9c3aea8e856290818a4bc9d286/src/proxy/src/sw.js#L190

我的理解是，因为构造 Response 的原因，没法带上`Set-cookie`头，所以要这样另外设置 cookie，但是如何保证不会出现这样的情况：
> 异步设置 Cookie 成功之前，响应已经交回给浏览器，浏览器解析响应里的 js 脚本，该脚本试图读取 Cookie，此时对 Cookie 的设置还未完成。

**Comment by EtherDream** [comment]
这个问题之前也考虑过，包括普通的 PWA 应用里也是存在的。因为 Cookie API 是同步的，而 Service Worker API 全是异步，所以设置 Cookie 后立即发请求的话，这个请求里是没有刚刚设置的 Cookie 的。

说到底还是 Cookie 的 API 太老旧了，至今没有提供异步的接口。

**Comment by Dixeran** [comment]
我尝试过等待 client 对设置 cookie 的消息回复 ACK 之后才提交响应，不过一来一回的时间开销非常可观。期待新的 [Cookie Store API](https://www.chromestatus.com/feature/5658847691669504) 🤷‍♂️
