### ISSUE TITLE
[question] bundle.debug.js 这个是怎么编译出来的？

### ISSUE THREAD

**Issue by RickyWong33** [EtherDream/jsproxy-browser#7]
想单步运行学习一下代码
不过目前项目`debug.sh`出来也是压缩混淆后的代码
工程直接用到了`bundle.debug.js`，请问这个是怎么生成的

总之不知道如何调试运行代码来贡献这个工程

还望指导说明

**Comment by EtherDream** [comment]
运行 debug.sh 编译的。前端打包部分还比较乱，一直没改进~
